theme: jekyll-theme-minimal
title: Sadaqat Faqih Mulla
description: This is Sadaqat's portfolio website where he explores multidisciplinarity in research and teaching across Education, Technology and Society...
